service_now:
  instance_name: "https://dev96535.service-now.com/"
  user_name: "systemuser1"
  password: "Password@1"

workflow:
  ncident_group_key_field: "u_prometheus_alertgroup_id"
  no_update_states: [6,7,8]
  incident_update_fields: ["comments"]

default_incident:
  assignment_group: "<assignment group>"
  category: "<Software>"
  cmdb_ci: "<configuration item>"
  comments: "<comments text>"
  company: "<company name>"
  contact_type : "<contact type>"
  description: "<description text>"
  impact: "2-High"
  short_description: "Test Alert from webhook"
  subcategory: "Operating System"
  urgency: "2-High"
